### ISSUE TITLE
Description is currently required

### ISSUE THREAD

**Issue by maclockard** [ashleygwilliams/wasm-pack#108]
when running `wasm-pack` when there is currently not a description prevents building. Would be nice if description was optional or documented as required:

    λ wasm-pack init
      [1/7] 🎯  Adding WASM target...
      [2/7] 🌀  Compiling to WASM...
      [3/7] 📂  Creating a pkg directory...
    missing field `description` for key `package`

**Comment by mgattozzi** [comment]
This was fixed in https://github.com/ashleygwilliams/wasm-pack/pull/65 which closed https://github.com/ashleygwilliams/wasm-pack/issues/43. This fix will be part of the upcoming 0.2 release! :D This should be coming out in the next few days. In the mean time you can use the master branch to avoid this issue by doing:

```bash
$ cargo install --git https://github.com/ashleygwilliams/wasm-pack
```
if you already have it installed you'll also need to add the `--force` flag to use the newer version
