### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by lukehedger** [ashleygwilliams/wasm-pack#85]
Trying to install with:
```
cargo install wasm-pack
```

Results in:
```
   Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing wasm-pack v0.1.0
   Compiling vec_map v0.8.0
   Compiling cfg-if v0.1.2
   Compiling stable_deref_trait v1.0.0
   Compiling lazy_static v1.0.0
   Compiling unicode-width v0.1.4
   Compiling memoffset v0.2.1
   Compiling serde v1.0.38
   Compiling glob v0.2.11
   Compiling itoa v0.4.1
   Compiling unicode-xid v0.0.4
   Compiling void v1.0.2
   Compiling dtoa v0.4.2
   Compiling ansi_term v0.11.0
   Compiling unicode-xid v0.1.0
   Compiling quote v0.3.15
   Compiling termcolor v0.3.6
   Compiling lazy_static v0.2.11
   Compiling rayon-core v1.4.0
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `rayon-core`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-pack v0.1.0`, intermediate artifacts can be found at `/var/folders/lt/21g7hfd10_7_b95nnh8_ymb40000gn/T/cargo-install.HSJZjCqOt4RL`

Caused by:
  build failed
```

**Comment by ashleygwilliams** [comment]
hi! sorry you are running into this @lukehedger - can you let me know what version of Rust you are on? what OS are you? i should be able to help you through this (i'm on mozilla/rust irc if you wanna talk sync, @ag_dubs)

**Comment by lukehedger** [comment]
Hey @ashleygwilliams - I've got the following versions:
```
rustc 1.25.0 (84203cac6 2018-03-25)
cargo 0.26.0 (41480f5cc 2018-02-26)
```

On macOS 10.13.2

Thanks for your help 🙂

**Comment by ashleygwilliams** [comment]
@lukehedger ok! how did you install rust? did you use `rustup`? i'm pretty sure this issue is a result of how you installed rust... the canonical way is this https://www.rust-lang.org/en-US/install.html

i'm pretty sure you are running into an issue where your computer does not have a c compiler installed (this would affect any rust you tried to compile, not just this project!), since you are on macOS, this should be solvable by installing the xcode command line tools- let me know if you need any help with that!

**Comment by lukehedger** [comment]
Ah thanks for this @ashleygwilliams - think it was perhaps a combination of `xcode` and my PATH not being setup correctly for `cargo`. Why is it always XCode?

Looking forward to using `wasm-pack` now - super cool project! 😎
